### ISSUE TITLE
Giant images on the screen every time website is loaded

### ISSUE THREAD

**Issue by bitfede** [cvgellhorn/webpack-boilerplate#7]
Hello @cvgellhorn ! First of all thanks for this cool boilerplate!!!

I only have a little issue, every time I reload or load the website. Basically the icons that I have on the top right of the cover page appear for a second or two in a giant format, then they disappear and re-appear correctly in their place in their correct measure.

Do you know what can this issue be? Where can I look into in order to start debugging?

Here is a screenshot, this happens for a second every time the page is loaded or refreshed. Then the correct homepage appears.

<img width="1280" alt="screen shot 2018-02-06 at 2 25 54 pm"  src="https://user-images.githubusercontent.com/15684622/35861841-c9e64b66-0b49-11e8-9c31-f3bb10187a52.png">

Thanks for the help!! :)

**Comment by cvgellhorn** [comment]
Hey @bitfede,

this behavior appears due to the css injection from webpack. All styles are loaded via js, so for a split second the styles are not applied till they're loaded and interpreted. If you want to prevent this behavior, you should use the [extract-text-webpack-plugin](https://github.com/webpack-contrib/extract-text-webpack-plugin) to extract all your styles into a bundled css file, which gets injected before all other scripts are loaded.

Cheers
Chris

**Comment by bitfede** [comment]
cool! Thank you!!!

another small question, in`/dist` I dont find a complete version of the web asset I built with `npm run build`  to deploy, only an incomplete folder. here a screenshot of the dist folder.

<img width="487" alt="screen shot 2018-02-09 at 1 23 31 pm" src="https://user-images.githubusercontent.com/15684622/36027656-7bb197e8-0d9c-11e8-8daf-02ead223ffe5.png">

opening `index.html` brings this up:
<img width="1233" alt="screen shot 2018-02-09 at 1 24 42 pm" src="https://user-images.githubusercontent.com/15684622/36027711-a578fbb6-0d9c-11e8-8279-0b24fee727b9.png">

thank you so much for taking the time to explain me, really appreciate :) 👍

**Comment by cvgellhorn** [comment]
Hey @bitfede,

you should look into this issue #2, there is an explanation for the missing images. :)

Cheers
Chris
