### ISSUE TITLE
`build` not copying certain image folders into `./dist`

### ISSUE THREAD

**Issue by markedup** [cvgellhorn/webpack-boilerplate#76]
I have the following project structure, which runs perfectly via `npm run dev`:

```
/project-name

  /assets

    /images
      /branding-icons
        [.gif files]
      /social
        [.png files]
      /stars
        [.png files]
      [various .svg, .jpg, .png files in root of /images]

    /styles
      /vendor
        [.css files]
      index.scss

    index.ejs
    ...
```

However, when I run `npm run build`, the `/branding-images` and `/stars` folders are ignored in the copy across; the `/social` sub-dir and all the file types in the root of `/images` copy over into `/dist` as expected.

I've looked at the Webpack configs, and I can't see anything obvious in there as to what's excluding certain directories from `build` that are served as expected from `dev`.

Any ideas?

*Tested on both macOS 10.13.6 and latest Windows 10 Pro.*

**Comment by cvgellhorn** [comment]
Hey @markedup,

you should look into this issue #2 , there is an explanation for the missing images. The dev build probably works because the assets are getting directly served from the original root directory.

Cheers
Chris

**Comment by markedup** [comment]
No, there are broken image links in the `/dist` version, which is how I discovered certain image folders aren't being copied over as part of `build`.

**Comment by cvgellhorn** [comment]
No, the file-loader runs over scss files and copies all image files with a specific build hash to the dist directory and renames the original linked file in the resulting css source. Copying all image files would result in wrong image caches on client machines.

Like I mentioned in my previous response, in the linked issue is an answer for the img tags in ejs files behaviour. In short, the ejs-loader doesn‘t support the file-loader, all img tags in your index file are beeing ignored. It only runs over scss files, because the sass-loader has file-loader support.

I never cared about the missing file-loader support in the ejs-loader, because I only use the index.ejs as an entry point for my applications and load everything afterwards.

If there is another problem with broken image links in your dist directory, you should probably look into current issues on the file-loader project page.

Cheers
Chris

**Comment by markedup** [comment]
Thanks for the clarification.
